version: '3.1'
services:
  sonarqube:
    image: sonarqube:7.9.1-community
    ports:
      - 9000:9000
#    depends_on:
#      - mysql-docker
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
    restart: always
    ulimits:
      nproc: 65535
      nofile:
        soft: 32000
        hard: 40000
    networks:
      - asgard

networks:
  asgard:
volumes:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
